### ISSUE TITLE
Fix GSI ncdiag -> ioda/ufo converter scripts to use NcWriter

### ISSUE THREAD

**Issue by shlyaeva** [JCSDA/ioda-converters#107]
Currently GSI ncdiag -> ioda/ufo obs/geovals files converter scripts do not use NcWriter. 
It would be beneficial to use NcWriter (in that case if the ioda file format changes we won't have to change the scripts).

**Comment by ADCollard** [comment]
OK, help me out here.   What is NCWriter and where do I find it?

I might re-assign to Cory!

ADC

**Comment by CoryMartin-NOAA** [comment]
I believe it's part of the IODA-converters python library, which I guess since I commented means I'm volunteering myself? haha

**Comment by ADCollard** [comment]
Yes, well volunteered Cory.

**Comment by CoryMartin-NOAA** [comment]
@srherbener 

I'm working on these modified Python scripts to generate IODA observation files from GSI diag files, and while I am able to get the ObsValue, PrepQC, and ObsError to write out successfully, I have not yet figured out how to output additional information that is used for the UFO tests (GSIHofX for example). As far as I know the code runs with no errors but the extra variables are not there when I run ncdump.

Does the NcWriter class not currently support this, or is there an extra step I need to do to get it to save these extra data?

If you'd like to look at my code so far, it's in ioda-converters/feature/gsi_ncwriter:
https://github.com/JCSDA/ioda-converters/blob/feature/gsi_ncwriter/src/gsi-ncdiag/conv.py#L119-L123

Thanks!

**Comment by CoryMartin-NOAA** [comment]
Never mind, I think I've figured out what I need to modify in ioda_conv_ncio to get this to work more generally. I'll test it and see if it matches what the original scripts produce.

**Comment by srherbener** [comment]
Hi @CoryMartin-NOAA, Sorry about the slow response. The NcWriter class in the develop branch needs a simple modification to accommodate additional obs data such as the H(x) values from GSI. Lines 345-350 in ioda_conv_ncio.py are, unfortunately, redundant and they can be replaced with:
* ObsVars[VarKey[1]][VarNum, LocNum-1] = VarVal
Once that is done, you should be able to add ObsValue, ObsError, PreQC as before to the ObsData dictionary, and then add in the other values. Sorry about this code fault, I think it evolved from a state where the if statements were actually doing something and I didn't notice that the if statements became redundant.

**Comment by srherbener** [comment]
Also, I think there is a potential performance issue with the manner in which the BuildNetcdf is organized. Every location becomes an entry in the ObsData dictionary so when we get to large data (GOES-16 full disc can have 100 million locations in one image) this seems like a bad situation. Inside BuildNetcdf, there is a call to another method called ExtractObs where the ObsData dictionary gets reformatted into another dictionary, ObsVars, which stores arrays with nlocs being one of the dimensions, which seems like a much better situation for satellite obs data. Would you agree with this concern?

I am thinking that the ExtractObs call needs to be pulled out of the BuildNetcdf method and BuildNetcdf would then take the output of ExtractObs as its inputs. Then the client calls ExtractObs or just builds the ObsVars and meta data dictionaries and doesn't call ExtractObs. This would also allow the client to append meta data to the meta data (scan angle, satellite angles, etc.) dictionaries that ExtractObs creates. Does this seem like a useful change?

Some history: The NcWriter class was originally designed to help with conventional obs. These obs tend to have missing values, such as a radiosonde ascent measures t, q, u, v but not all four at the same time. This means that at some locations you can have only t and q and other locations you can have only u and v. Additionally, the obs come in a list in some input files where the same location is repeated for the t and q measured at the same time. The ObsData dictionary with its location key helps collect obs that have the same locations and to figure out where the missing values go. This is great for conventional obs but perhaps not so great for satellite obs. It seems that the output of the current ExtractObs, ie the ObsVars dictionary, is much more amenable to satellite data.

What I'm thinking with my refactoring of the BuildNetcdf method is that if you have conventional data, you build the ObsData dictionary  and call both ExtractObs and BuildNetcdf. If you have satellite data, you build the ObsVars dictionary and the meta data dictionaries and just call BuildNetcdf.

What are your thoughts about this? Am I looking at this in the right way or do you think there is another approach that could be taken to help with the satellite obs handling?

If you want we can set up a google hangout to discuss this further.

**Comment by svahl991** [comment]
My feeling, at least regarding the ODB2 converter I've been working on, is that it might be easier in the long run to just have one "path" to importing the data, rather than have one process for conventional obs and a different process for satellite data. I see the problem Steve H. describes with the dictionary structure we used for conventional obs when you try to apply it to satellite obs, so we'll probably need to do something different. But then I'll probably use that "different" path for conventional obs as well. Given the way that ODB2 files are structured, this may mean that I'll have to do something more complex than just walking through the file row-by-row a single time, but if I have to write the code to do it differently for satellite data, then I should be able to use the same code for the conventional obs, too.
Just sharing my thoughts.  Obviously, if you provide an external ExtractObs method then other converters can choose to use it, but I don't know if I will for the ODB2 converter.
I'd be up for a Google hangout discussion on this topic.

**Comment by CoryMartin-NOAA** [comment]
@srherbener Thanks. That line/area of the code is where I was looking at as well, I might have made it slightly more complicated than that by including a new loop, but at least it's working for now.

I agree that the NcWriter class will have performance issues going forward. I've already noticed that (and correct me if there's a better way to do this) that while we can use numpy indexing to grab data and put into arrays, I do not know how to put the observations into the dictionary (before calling BuildNetcdf) without using a loop, which is much slower than numpy. 
(https://github.com/JCSDA/ioda-converters/blob/feature/gsi_ncwriter/src/gsi-ncdiag/conv.py#L112-L123) 

I think your suggestion sounds good. Satellite data will be on a grid and thus fit into an array nicely, and then the user can choose when they are writing their calls to the API whether or not to use the ObsData dictionary or just build Obsvars seprately.

**Comment by CoryMartin-NOAA** [comment]
I've pushed a first beta draft version of the reworked conversion scripts for GSI diag -> GeoVaLs and IODA obs (the latter using NcWriter) that are more generic (should work for any date) and use Python multiprocessing to run in parallel and not sequentially (each diag file is a separate process). It's still a work in progress, but I think it's usable for conv/rad files (no subsetting yet) in feature/gsi_ncwriter.  Use the top-level script:   /scratch4/NCEPDEV/da/save/Cory.R.Martin/JEDI/src/ioda-converters_2/src/gsi-ncdiag/proc_gsi_ncdiag.py.  I want to hold off on merging until I've been able to further tweak and test it.

**Comment by srherbener** [comment]
@CoryMartin-NOAA, thanks for posting your scripts. I took a look at the feature/gsi_ncwriter branch from a day or two ago. I think it looks good. 

There is one thing where the location key is getting loaded up with a lot of pieces of data, the setting of LocKeyList. I didn't intend for the location key to be anything else but (x,y,z,t) values that correspond to independent variables of atmospheric/oceanic fields. However, I realize that the NcWriter class, in the develop branch, doesn't give you the means to get those extra metadata quantities in the file. This is one of the reasons I want to refactor BuildNetcdf. @svahl991 and I had a discussion a couple days ago about loading up the location key and we think from a functional perspective it's safe to do this, but I'm concerned that this could be quite detrimental to performance (ie, have a dictionary key that is a tuple with 7 or 8 elements). 

I'm okay with loading up the location key for the short term solution, but I think we need to do this differently in the long term. I like the methodology of doing many small incremental merges, as opposed to big merges every once in a while, so I'm also okay with merging in your code with the loaded up location key and addressing this in a subsequent pull request.

**Comment by CoryMartin-NOAA** [comment]
@srherbener I also noticed that the first time I tried to run these scripts, the number of observations that were written out was slightly (maybe 5%) smaller than what were written out from the previous versions of the scripts. I traced it to the length of the dictionary not being the same as the number of matching obs added to the dictionary and think it's because some of them (at least for conventional obs) had the same set of location keys (which is definitely plausible), so I added a extra index LocKey to ensure they all were included. I'm not sure if that is something to keep in mind as this is refactored or not.

I also could not use VarMetaData (issue #100 ?) for things like frequency, etc. in the radiances.py file and had to further modify NcWriter (by faking a LocKey that is not an actual location), but I also think that my solution is not very elegant nor the best way to do it and should be redone in the future.

I'll add the ozone and AOD capabilities later today (should mostly be copy and paste what I already have) to match what is already available in the current scripts and then I can do a pull request to develop after that.

**Comment by srherbener** [comment]
@CoryMartin-NOAA, I'm a little bit concerned about the need to add an extra index LocKey in order to get the same nlocs count as before. This is suggesting that there are locations (x,y,t) or (x,y,z,t) where there are multiple values for one observation variable (outside of the usual reasons such as multiple channels on an instrument). I wouldn't expect this to happen (unless I have a misconception about what locations mean). Could it be, at the places where LocKey tuples matched, there is some other issue such as two channels or two variables being treated as the same?

**Comment by CoryMartin-NOAA** [comment]
@srherbener yeah I think it is likely an issue with the time variable but I'm not sure. I'm still finding some small bugs in these scripts that I thought I had resolved. Hopefully I can get them working properly soon.

**Comment by CoryMartin-NOAA** [comment]
@travissluka I noticed this morning that I also had issues with my converters, which I traced back to a difference between the ioda_con_ncio develop branch version and my own and the way it defines the datetime str dimension. Referencing @ #127 I think some greater flexibility or at least clarification on the way this class handles timestamps would be great.

**Comment by CoryMartin-NOAA** [comment]
@srherbener regarding the LocKey issue, I thought it was just related to matching station IDs or something like that, but I'm not sure what it is now. @ADCollard noticed missing data in the output of radiance obs files that I had generated and I've traced the issue back to again the LocKeys. Without an ObsCount, the number of obs written out is Nobs = Nlocs instead of Nobs = Nlocs*Nchans but I don't understand why. I've reopened the feature/gsi_ncwriter branch but have not started a pull request.
