### ISSUE TITLE
Question about installing the ioda-converters to the build directory

### ISSUE THREAD

**Issue by flampouris** [JCSDA/ioda-converters#139]
Hello @srherbener,

I have a fast question; when I am updating something to the ioda-converters and I have already built the system, how can I update the content of the [...]/build/bin ? 

Thank you,
Stelios

**Comment by srherbener** [comment]
Hi @flampouris,

I think you are asking about something I just noticed for the first time yesterday. When a change in a source file is made and a "make" or "make install" is run, the install location is updated but the subdirectory "bin" in the build directory is not. Is this what you are asking about?

I think this is a defect in the build system, probably due to a CMakeLists.txt file not coded correctly. I'll look into this.

In the meantime, the only way I know of to make the update happen is to wipe out the build directory and rebuild from scratch. Fortunately, in ioda-converters this can be done quickly.

**Comment by flampouris** [comment]
Hello @srherbener, the issue is exactly as you described it and yes, we use similar solution.
