### ISSUE TITLE
Inconvenient to have a single variable per IODA obs file

### ISSUE THREAD

**Issue by svahl991** [JCSDA/ioda-converters#151]
The netCDF IODA files that are created from the GSI conversion scripts for conventional obs contain a single observation variable. For example, the sonde data for 0Z 15 April 2018 comes in four different files, one each for each variable. By comparison, the test netCDF sonde files that are in the IODA repository contain t, q, u, and v all in one file. 

It came up in our group meeting this week that having each variable in a separate file makes it more difficult for the scientists to perform certain types of analysis. For example, I think the data from a particular profile is spread out amongst the different files and it seems non-trivial to match up the locations. I'm not totally clear on the exact specifics of the problems this is causing for the scientists; perhaps they can chime in.

I just wanted to enter this issue so that we could discuss what the simplest and best solution is. Some thoughts I've had:
* Is it possible to read the four files into IODA and then use IODAIO to output them to a single file? Or do they all go into different ObsSpaces so that won't work?
* Is it easy/reasonable for the converter script to merge the data and output a single file?
* Do we need to create a separate "merge" script?
* Other ideas?

**Comment by CoryMartin-NOAA** [comment]
@shlyaeva 's old scripts had a final merge script for the conventional data from GSI. This can likely be modified to work with these output files. The reason why I didn't combine them in the scripts I created was that I was not sure how a missing observation would be handled, and if the order is still the same, particularly for aircraft. The number of locations for the different variables for sondes, for example, is different. I hope this is real and not an artifact of something the script is doing incorrectly.

**Comment by shlyaeva** [comment]
@CoryMartin-NOAA, @svahl991: the old script that was merging t, u, v, q did something like this:
- take *t* file, add netcdf variables named u, v, q filled in with missing values to the file.
- find the locations (lat-lon-pressure-time) in *uv* file that match with locations in *t* file. For those, copy u, v variables from *uv* file to *t* file and put a missing value in *uv* file (so they are not double-accounted in two files).
- do same with *q* file.
- if after this process there are obs that are not set to missing value in *uv* or *q* files, keep those files, otherwise they can be removed.

I agree with Cory, the script should be modifiable to work with the new output files.

**Comment by srherbener** [comment]
This is the purpose of the location keys in the dictionary that is passed to the ExtractObsData method in NcWriter. By using unique tuples for location keys you can collect up t, q, u, v values that are at the same location and then know where the missing values belong. That is, if a particular location only has t and q values, then you know that the u and v values are missing for that location. 

Note that this allows you to simply stream the input t, q and uv files together and get all four variables into one output file. The idea would be to:
* For the t, q and uv files, open the file, construct the record and location keys for each observation value and place into the dictionary.
* call the ExtractObsData method in NcWriter
* call the BuildNetcdf method in NcWriter

For examples, the ODB converters and most of the marine converters are following this algorithm.

I think with some recent changes to NcWriter, we will get netcdf default fill values for missing values which is what we want for the eventual missing value handling.

The record keys will keep profiles grouped together. Other than that, I'm not sure if there are any additional obs data orderings that are required.

If there are more requirements for ordering obs data, please let me know so we can address them.

**Comment by CoryMartin-NOAA** [comment]
@srherbener ok so if I understand correctly, rather than writing a script to combine the observations after processing them from GSI->IODA, instead open multiple GSI diag files at once and output "sfc_obs" which is T,U,V all in that one IODA file. 

Is there a need to have both the capability to have one observation variable (ex. Temp) to one IODA file as well as all variables in one, or would just combining them satisfy everyone's conditions? The only real advantage I can think of of using separate files would be access speed and file size. If it's the latter, I can just modify the gsi-ncdiag scripts, but if the former, I would either need to add in an option for separate/combined or have two different scripts to do each (I prefer the option method)

**Comment by srherbener** [comment]
@CoryMartin-NOAA, my understanding is that we do not need to have one obs variable per IODA file, and that combining all variables into one file is preferred. Do you agree @shlyaeva?

Given that we want one file with all variables as the output, I think that it's okay to take whatever path is easiest whether it's convert separate files to IODA in one script first then combine in another script, or read in multiple files and convert/combine in one script.

**Comment by shlyaeva** [comment]
@srherbener: I agree (also based on @svahl991's input here), we'd like to have all variables in one file.

**Comment by svahl991** [comment]
Just to confirm what others are saying: I'm mostly going off what I've heard from @YaliWu0219 and @junmeiban , but I haven't heard anyone talk about any advantages of having the individual variables in separate files. Only disadvantages.

**Comment by CoryMartin-NOAA** [comment]
@srherbener @shlyaeva ok sounds good. Once the current pull request is approved, I'll start a new branch to work on the record number for profiles as well as this issue. I think it should be all combined in the main step if that is what people want, and save the extra step of concatenation, but I don't yet know how to do this the best way with the classes I've written (since they assume one input file). Let me think about it for a bit, or feel free to offer any suggestions.

**Comment by CoryMartin-NOAA** [comment]
Yeah on second thought, I think it's going to be more efficient to have a concatenation step. Because the GSI output is by variable and not by platform for conventional data, it would require reading in all of the conv files at the same time. To ensure that it's matching locations and missing data, I can use the ncwriter class to write it out after reading in a specified number of input files that have previously been written, rather than simply using something like ncks.

**Comment by CoryMartin-NOAA** [comment]
Pull request #166 will finish up this and resolve it, should work for conventional data. Will have capability to concatenate GeoVaLs soon.
