### ISSUE TITLE
A qustion about combine_conv.py

### ISSUE THREAD

**Issue by junmeiban** [JCSDA/ioda-converters#168]
I have a question about the script combine_conv.py  #166
I checked the results from single file(the single file is generated by proc_gsi_ncdiag.py  #147.) and combined file. The following figures are virtual temperature from single file(upper panel) and combined file(lower panel). It looks the observation number for Tv has reduced after combining. 
![Screen Shot 2019-05-10 at 1 29 47 PM](https://user-images.githubusercontent.com/23242703/57552432-17b37100-7329-11e9-87c8-d750d3f87d21.png)
![Screen Shot 2019-05-10 at 1 30 00 PM](https://user-images.githubusercontent.com/23242703/57552438-1aae6180-7329-11e9-86f0-ee861d860026.png)

**Comment by junmeiban** [comment]
@CoryMartin-NOAA

**Comment by CoryMartin-NOAA** [comment]
@junmeiban  thanks for noticing this. I think it's been fixed. It was the result of an attempt to make the code run quickly but with this new loop it still finishes for all of the sondes data in around a minute.
I tried it now for sondes_tv and sondes_tsen and there are 6 obs difference from the sum of the original two. They are thrown out because they are (and I checked) at the same lat,lon,time,height,pressure and are both for Tv. I will link a pull request to this issue ASAP.

**Comment by junmeiban** [comment]
Thank you so much to fix it.

**Comment by shlyaeva** [comment]
@junmeiban, @CoryMartin-NOAA: is this fixed, can this issue be closed?

**Comment by CoryMartin-NOAA** [comment]
@shlyaeva As far as I know. I'll close it but if we still notice a problem (like with a different observation set), we can reopen it in the future.
