### ISSUE TITLE
question about sensible T of radiosonde data below 400hpa

### ISSUE THREAD

**Issue by junmeiban** [JCSDA/ioda-converters#173]
I converted “diag_conv_t_ges.2018041500_ensmean.nc4” (from http://data.jcsda.org/gsi_diags_2018041500.tar) to ioda obs by using proc_gsi_ncdiag.py .
I checked the output file: sondes_tsen_obs_2018041500.nc4. It looks that sensible T below 400hpa is filtered out. 
There are some discussions about this issue on #147. 
My question is why sensible T of sondes below 400hpa is filtered out. 
![pro_sondes_tsen_obs_2018041500_air_temperature](https://user-images.githubusercontent.com/23242703/57156474-4ebedb00-6d9b-11e9-9847-cd265a85f1cc.png)

**Comment by shlyaeva** [comment]
cc-ing from the pull request answers (which don't answer the question definitively):
Cory: "Perhaps it's an issue of the way these two quantities are reported in the BUFR files or the way GSI handles them (Tsen~Tv at upper levels where moisture content is small could be a theory?)"
Me: "This issue is not in the ioda-converter scripts, but in the way GSI uses radiosonde data (or maybe in the way prepbufr data are prepared).
@ADCollard: do you know why there are only few observations of radiosonde tsen below 400hPa in GSI?"

**Comment by ADCollard** [comment]
Sorry for the slow reply to this, but I had to look at the code myself to check (sorry but I am a satellite guy!),

From what I can tell, in the GSI the data is read in as a virtual temperature from PrepBUFR if it is available, and one of the criteria for it to be available is a coincident humidity observation.  I think that explains why most of the tsens are for levels above 400hPa.

There are so many quirks with conventional processing that issues like this are likely to come up a lot.

**Comment by junmeiban** [comment]
Thank you so much for your explanation. 
I think this issue can be closed.
