### ISSUE TITLE
Missing value handling in gnssro converter needs update

### ISSUE THREAD

**Issue by jjguerrette** [JCSDA/ioda-converters#233]
It is possible that, by removing the test formerly on line 316 of ioda/src/fileio/NetcdfIO.cc (IODA PR [365](https://github.com/JCSDA/ioda/pull/365)), i.e.,
![image](https://user-images.githubusercontent.com/20328709/68978640-9269b700-07b8-11ea-82ea-992b4c4ecbb8.png)
values that should be recognized as missing in gnssro obs files (`-9.899999e+15`) are no longer recognized as missing.  Without setting a minimum bound  of `-10.0` on gnssro refractivity, my mpas-jedi 3denvar simulation quits during a Background Check.  When I add that bound, the simulation proceeds without a problem.  The associated converter line is here:

https://github.com/JCSDA/ioda-converters/blob/aa9426dc79502b1832e8425b31f716315a6fc027/src/gnssro/gnssro_bufr2ioda.f90#L82

**Comment by jjguerrette** [comment]
Notably, there are no missing refractivity values in the small gnssro test file.  That is the only file used for the `GnssroRef` operator in gnssroref.yaml.  The medium and large files do not contain refractivity.

**Comment by hailingz** [comment]
Could you @jjguerrette please try the branch feature/gnssro_missing_value in which I added the 
_Fillvalue? I have some trouble using the Cheyenne netcdf4-python module when doing ioda-converter. Executing bufr2nc.py script gave me "ImportError: No module named ncepbufr". 
Do you have any advice on the python netcdfbufr?

@srherbener 
Do you know if adding "_Fillvalue" in the ioda netcdf file should be the solution? Thanks

**Comment by srherbener** [comment]
@jjguerrette and @hailing, the IODA reader should recognize the fill value attribute and substitute the JEDI missing values accordingly. I believe that the 'v' is capitalized in the attribute name. Here's the netcdf doc excerpt:

----------------

_FillValue

The _FillValue attribute specifies the fill value used to pre-fill disk space allocated to the variable. Such pre-fill occurs unless nofill mode is set using nc_set_fill(). The fill value is returned when reading values that were never written. If _FillValue is defined then it should be scalar and of the same type as the variable. If the variable is packed using scale_factor and add_offset attributes (see below), the _FillValue attribute should have the data type of the packed data.

It is not necessary to define your own _FillValue attribute for a variable if the default fill value for the type of the variable is adequate. However, use of the default fill value for data type byte is not recommended. Note that if you change the value of this attribute, the changed value applies only to subsequent writes; previously written data are not changed.

Generic applications often need to write a value to represent undefined or missing values. The fill value provides an appropriate value for this purpose because it is normally outside the valid range and therefore treated as missing when read by generic applications. It is legal (but not recommended) for the fill value to be within the valid range.

Note that if you change the value of this attribute, the changed value applies only to subsequent writes; previously written data are not changed.

**Comment by jjguerrette** [comment]
Thank you @hailingz, @junmeiban, and @srherbener for your quick work.  Have a great weekend!
