### ISSUE TITLE
gsi-ncdiag converter: Add units to variables

### ISSUE THREAD

**Issue by markjolah** [JCSDA/ioda-converters#245]
Many of the IODA files produced by the `gsi-ncdiag` converter program are not adding units to the variables.  The existence of units in each IODA file can be confirmed with `ncdump -h <file>`, which will list any units specified.  Most likely for each IODA file, the variables in groups `@ObsValue`, `@ObsError`, `@GsiHofx`, `@GsiHofxBc`, `@GsiFinalObsError`, `@GsiAdjustObsError` should all have the units specified.  Each file seems to have a different subset of variables with and without units.

**Comment by emilyhcliu** [comment]
@markjolah @cyberbass The updated obs files for 2019070100 can be found on s4 at the following location: /data/users/eliu/AOP75/2019070100_new/obs

Things fixed in this updated data set are:
(1) Removed obsolete "nrecs" dimension from obs files 
(2) **Added units to GSI reference variables (e.g., @GsiHofX)**
(3) Added  @GsiHofX and @GsiHofXBc for sea surface temperature in SSTS obs file

Please let me know if this new set of obs files work for jedi-rapids.

**Comment by emilyhcliu** [comment]
@markjolah @cyberbass 
I was not able to generate the **geoval** file for sst correctly. I am debugging now. This will not affect jedi-rapids run since we only need obs files.

**Comment by markjolah** [comment]
I'm not sure if this is still an issue, reopen if so.
